# Generated by Django 5.2 on 2025-04-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pushlog", "0002_push_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="push",
            name="tags",
            field=models.ManyToManyField(to="pushlog.tag"),
        ),
    ]
