ACCESS_GROUPS_CONFIG = {
    "SCM_ALLOW_DIRECT_PUSH": {
        "permission": "scm_allow_direct_push",
        "active_group": "active_scm_allow_direct_push",
        "expired_group": "expired_scm_allow_direct_push",
        "membership_group": "all_scm_allow_direct_push",
        "display_name": "Above Level 3 Commit Access",
    },
    "SCM_LEVEL_3": {
        "permission": "scm_level_3",
        "active_group": "active_scm_level_3",
        "expired_group": "expired_scm_level_3",
        "membership_group": "all_scm_level_3",
        "display_name": "Level 3 Commit Access",
    },
    "SCM_LEVEL_2": {
        "permission": "scm_level_2",
        "active_group": "active_scm_level_2",
        "expired_group": "expired_scm_level_2",
        "membership_group": "all_scm_level_2",
        "display_name": "Level 2 Commit Access",
    },
    "SCM_LEVEL_1": {
        "permission": "scm_level_1",
        "active_group": "active_scm_level_1",
        "expired_group": "expired_scm_level_1",
        "membership_group": "all_scm_level_1",
        "display_name": "Level 1 Commit Access",
    },
    "SCM_VERSIONCONTROL": {
        "permission": "scm_versioncontrol",
        "active_group": "active_scm_versioncontrol",
        "expired_group": "expired_scm_versioncontrol",
        "membership_group": "all_scm_versioncontrol",
        "display_name": "scm_versioncontrol",
    },
    "SCM_CONDUIT": {
        "permission": "scm_conduit",
        "active_group": "active_scm_conduit",
        "expired_group": "expired_scm_conduit",
        "membership_group": "all_scm_conduit",
        "display_name": "scm_conduit",
    },
    "SCM_L10N_INFRA": {
        "permission": "scm_l10n_infra",
        "active_group": "active_scm_l10n_infra",
        "expired_group": "expired_scm_l10n_infra",
        "membership_group": "all_scm_l10n_infra",
        "display_name": "scm_l10n_infra",
    },
    "SCM_NSS": {
        "permission": "scm_nss",
        "active_group": "active_scm_nss",
        "expired_group": "expired_scm_nss",
        "membership_group": "all_scm_nss",
        "display_name": "scm_nss",
    },
    "SCM_FIREFOXCI": {
        "permission": "scm_firefoxci",
        "active_group": "active_scm_firefoxci",
        "expired_group": "expired_scm_firefoxci",
        "membership_group": "all_scm_firefoxci",
        "display_name": "scm_firefoxci",
    },
}
