# Generated by Django 5.2 on 2025-05-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("headless_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationjob",
            name="error",
            field=models.TextField(blank=True, default=""),
        ),
    ]
