# Generated by Django 5.2.1 on 2025-05-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("headless_api", "0002_automationjob_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationjob",
            name="relbranch_commit_sha",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="automationjob",
            name="relbranch_name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
