# Generated by Django 5.2 on 2025-05-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("headless_api", "0002_automationjob_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationjob",
            name="relbranch_specifier",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
