# Generated by Django 5.2.1 on 2025-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("headless_api", "0003_automationjob_relbranch_commit_sha_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("add-commit", "Add commit"),
                    ("tag", "Tag"),
                    ("merge-onto", "Merge onto"),
                ]
            ),
        ),
    ]
