# Generated by Django 5.2.3 on 2025-06-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("headless_api", "0004_alter_automationaction_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("add-commit", "Add commit"),
                    ("add-commit-base64", "Add base64 commit"),
                    ("create-commit", "Create commit"),
                    ("tag", "Tag"),
                    ("merge-onto", "Merge onto"),
                ]
            ),
        ),
    ]
