# Generated by Django 5.2.4 on 2025-08-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("headless_api", "0005_alter_automationaction_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationjob",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("IN_PROGRESS", "In progress"),
                    ("DEFERRED", "Deferred"),
                    ("FAILED", "Failed"),
                    ("LANDED", "Landed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default=None,
                max_length=32,
                null=True,
            ),
        ),
    ]
