# Generated by Django 5.2.4 on 2025-09-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("headless_api", "0006_alter_automationjob_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("SUBMITTED", "Submitted"),
                    ("IN_PROGRESS", "In progress"),
                    ("DEFERRED", "Deferred"),
                    ("FAILED", "Failed"),
                    ("LANDED", "Landed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="CREATED",
                max_length=32,
            ),
        ),
    ]
