# Generated by Django 6.0.6 on 2026-07-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headless_api', '0008_alter_automationjob_requester_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationjob',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('IN_PROGRESS', 'In progress'), ('DEFERRED', 'Deferred'), ('FAILED', 'Failed'), ('LANDED', 'Landed'), ('CANCELLED', 'Cancelled'), ('ABORTED', 'Aborted')], db_index=True, default='CREATED', max_length=32),
        ),
    ]
