# Generated by Django 5.2.5 on 2025-09-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("headless_api", "0008_alter_automationjob_requester_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("add-commit", "Add commit"),
                    ("add-commit-base64", "Add base64 commit"),
                    ("create-commit", "Create commit"),
                    ("tag", "Tag"),
                    ("merge-onto", "Merge onto"),
                    ("merge-remote", "Merge commit from remote repository"),
                ]
            ),
        ),
    ]
