# Generated by Django 6.0.6 on 2026-09-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("headless_api", "0009_alter_automationjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationjob",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="automationjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
