# Generated by Django 5.0.6 on 2024-05-10 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="landingjob",
            old_name="revisions",
            new_name="unsorted_revisions",
        ),
    ]
