# Generated by Django 5.0rc1 on 2023-12-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_repo_worker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingjob",
            name="repository_name",
        ),
        migrations.RemoveField(
            model_name="landingjob",
            name="repository_url",
        ),
        migrations.RemoveField(
            model_name="revision",
            name="patch_bytes",
        ),
        migrations.AddField(
            model_name="landingjob",
            name="target_repo",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.repo"
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="commit_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="revision",
            name="patch",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="landingjob",
            name="landed_commit_id",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="landingjob",
            name="requester_email",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="landingjob",
            name="target_commit_hash",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="repo",
            name="system_path",
            field=models.FilePathField(
                allow_folders=True,
                blank=True,
                default="",
                max_length=255,
                path="/mediafiles/repos",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="revision",
            name="diff_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="revision",
            name="patch_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="revision",
            name="revision_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
