# Generated by Django 5.0.7 on 2024-08-14 18:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_profile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="approval_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repo",
            name="autoformat_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repo",
            name="commit_flags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(blank=True, max_length=32), size=None
                ),
                blank=True,
                default=None,
                null=True,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="force_push",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repo",
            name="is_phabricator_repo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="milestone_tracking_flag_template",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="repo",
            name="product_details_url",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="repo",
            name="push_bookmark",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="repo",
            name="required_permission",
            field=models.CharField(default=""),
        ),
        migrations.AddField(
            model_name="repo",
            name="short_name",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="repo",
            name="pull_path",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="repo",
            name="push_path",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="repo",
            name="url",
            field=models.CharField(),
        ),
    ]
