# Generated by Django 5.0.6 on 2024-06-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_profile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="system_path",
            field=models.FilePathField(
                allow_folders=True,
                blank=True,
                default="",
                max_length=255,
                path="/files/repos",
            ),
        ),
    ]
