# Generated by Django 5.0.7 on 2024-07-30 00:05

import django.db.models.deletion
from django.db import migrations, models

import lando.main.models.repo


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_landingjob_unsorted_revisions"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("permission", models.CharField(max_length=255, unique=True)),
                ("active_group", models.CharField(max_length=255)),
                ("expired_group", models.CharField(max_length=255)),
                ("membership_group", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="repo",
            name="approval_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repo",
            name="autoformat_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repo",
            name="commit_flags",
            field=lando.main.models.repo.ListOfTuplesField(default=[]),
        ),
        migrations.AddField(
            model_name="repo",
            name="force_push",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repo",
            name="is_phabricator_repo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="milestone_tracking_flag_template",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="repo",
            name="product_details_url",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="repo",
            name="push_bookmark",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="repo",
            name="repo_type",
            field=models.CharField(
                choices=[("git", "Git"), ("hg", "Mercurial")],
                default="hg",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="short_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="repo",
            name="access_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.accessgroup",
            ),
        ),
    ]
