# Generated by Django 5.1 on 2024-08-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_repo_approval_required_repo_autoformat_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="scm",
            field=models.CharField(
                blank=True,
                choices=[("hg", "Mercurial"), ("git", "Git")],
                default=None,
                max_length=3,
                null=True,
            ),
        ),
    ]
