# Generated by Django 5.1 on 2024-09-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_repo_system_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="scm",
            field=models.CharField(
                choices=[("hg", "Mercurial"), ("git", "Git")],
                default="hg",
                max_length=3,
            ),
        ),
    ]
