# Generated by Django 5.1.1 on 2024-09-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_worker_scm"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="encrypted_phabricator_api_key",
            field=models.BinaryField(blank=True, default=b""),
        ),
    ]
