# Generated by Django 5.1.3 on 2024-12-17 01:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_rename_repo_scm_scm_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="repo",
            old_name="push_bookmark",
            new_name="push_target",
        ),
    ]
