# Generated by Django 5.1.4 on 2025-01-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_repo_scm_type_alter_worker_scm"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diffwarning",
            old_name="error_breakdown",
            new_name="data",
        ),
    ]
