# Generated by Django 5.1.4 on 2025-01-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_rename_error_breakdown_diffwarning_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repo",
            name="is_initialized",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="ssh_private_key",
        ),
    ]
