# Generated by Django 5.1.4 on 2025-01-27 18:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_remove_repo_is_initialized_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="commit_flags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(blank=True, max_length=100), size=None
                ),
                blank=True,
                default=None,
                null=True,
                size=2,
            ),
        ),
    ]
