# Generated by Django 5.1.4 on 2025-01-29 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_repo_commit_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="legacy_source",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_target",
                to="main.repo",
            ),
        ),
    ]
