# Generated by Django 5.1.5 on 2025-01-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_repo_commit_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="default_branch",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
