# Generated by Django 5.1.4 on 2025-02-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_repo_legacy_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="pushlog_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
