# Generated by Django 5.1.7 on 2025-03-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_repo_legacy_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="short_name",
            field=models.CharField(blank=True, unique=True),
        ),
    ]
