# Generated by Django 5.1.6 on 2025-03-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_repo_legacy_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="automation_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
