# Generated by Django 5.1.7 on 2025-03-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_repo_automation_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_automation_user",
            field=models.BooleanField(default=False),
        ),
    ]
