# Generated by Django 5.1.7 on 2025-04-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_repo_pushlog_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_automation_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repo",
            name="automation_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
