# Generated by Django 5.2 on 2025-04-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_repo_commit_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="automation_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
