# Generated by Django 5.2 on 2025-04-25 16:22

import django.db.models.deletion
from django.db import migrations, models

import lando.main.models.repo


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_repo_automation_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="legacy_source",
            field=models.OneToOneField(
                blank=True,
                help_text="If this repo was migrated from a legacy (hg) repo, setting the value here will automatically retarget revisions to this repo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_target",
                to="main.repo",
            ),
        ),
        migrations.AlterField(
            model_name="repo",
            name="pull_path",
            field=models.CharField(
                blank=True,
                help_text="The path that the landing worker should pull from when landing.",
            ),
        ),
        migrations.AlterField(
            model_name="repo",
            name="push_path",
            field=models.CharField(
                blank=True,
                help_text="The path that the landing worker should push to when landing.",
            ),
        ),
        migrations.AlterField(
            model_name="repo",
            name="required_permission",
            field=models.CharField(
                default="",
                help_text="The permission required to be able to land to this repo. For example, main.scm_conduit.",
            ),
        ),
        migrations.AlterField(
            model_name="repo",
            name="scm_type",
            field=models.CharField(
                blank=True,
                choices=[("git", "Git"), ("hg", "Mercurial")],
                default=None,
                help_text="Automatically detected upon saving, will match the type of the remote repo.",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="repo",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="Should match the shortname field on Phabricator for this repo.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="repo",
            name="system_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="An automatically generated path on the landing worker instance, used to store the contents of the repo.",
                max_length=255,
                validators=[lando.main.models.repo.validate_path_in_repo_root],
            ),
        ),
    ]
