# Generated by Django 5.2.1 on 2025-06-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_repo_legacy_source_alter_repo_pull_path_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("git_hash", models.CharField(default="")),
                ("hg_hash", models.CharField(default="")),
                ("git_repo_name", models.CharField(default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="repo",
            name="github_repo_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Automatically generated based on the url field.",
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="hgmo_repo_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Automatically generated based on the url field.",
            ),
        ),
    ]
