# Generated by Django 5.2.1 on 2025-06-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_repo_legacy_source_alter_repo_pull_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="hooks_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
