# Generated by Django 5.2.1 on 2025-05-08 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_repo_legacy_source_alter_repo_pull_path_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("git_hash", models.CharField(default="")),
                ("hg_hash", models.CharField(default="")),
                (
                    "git_repo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.repo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
