# Generated by Django 5.2 on 2025-06-18 00:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_repo_hooks_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingjob",
            name="repository_name",
        ),
        migrations.RemoveField(
            model_name="landingjob",
            name="repository_url",
        ),
    ]
