# Generated by Django 5.2.1 on 2025-06-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_remove_landingjob_repository_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("git_hash", models.CharField(default="", unique=True)),
                ("hg_hash", models.CharField(default="", unique=True)),
                ("git_repo_name", models.CharField(default="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
