# Generated by Django 5.2.4 on 2025-07-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_commitmap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingjob",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("IN_PROGRESS", "In progress"),
                    ("DEFERRED", "Deferred"),
                    ("FAILED", "Failed"),
                    ("LANDED", "Landed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="type",
            field=models.CharField(
                choices=[
                    ("LANDING", "Landing worker"),
                    ("AUTOMATION", "Automation worker"),
                ],
                default="LANDING",
            ),
        ),
    ]
