# Generated by Django 5.2.4 on 2025-08-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_alter_landingjob_status_worker_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="attributes_override",
            field=models.TextField(
                blank=True,
                default="* !diff\n",
                help_text="SCM-specific attribute override. For git, this is documented in `gitattributes(5)`.",
            ),
        ),
    ]
