# Generated by Django 5.2.4 on 2025-09-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_upliftassessment_upliftrevision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("IN_PROGRESS", "In progress"),
                    ("DEFERRED", "Deferred"),
                    ("FAILED", "Failed"),
                    ("LANDED", "Landed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="SUBMITTED",
                max_length=32,
            ),
        ),
    ]
