# Generated by Django 5.2.4 on 2025-09-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_alter_landingjob_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingjob",
            name="requester_email",
            field=models.CharField(default="", max_length=255),
        ),
    ]
