# Generated by Django 5.2.7 on 2025-10-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_alter_landingjob_requester_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="revision",
            name="commit_id",
        ),
    ]
