# Generated by Django 5.2.7 on 2025-10-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_alter_landingjob_requester_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisionlandingjob",
            name="commit_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
