# Generated by Django 5.2.5 on 2025-10-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_alter_landingjob_requester_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="pull_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
