# Generated by Django 5.2.6 on 2025-10-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_alter_landingjob_requester_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="Repository name on other systems: Phabricator (`shortname`), and Treestatus.",
                unique=True,
            ),
        ),
    ]
