# Generated by Django 5.2.4 on 2025-09-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0031_alter_landingjob_requester_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="try_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
