# Generated by Django 5.2.4 on 2025-09-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_repo_try_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="type",
            field=models.CharField(
                choices=[
                    ("LANDING", "Landing worker"),
                    ("AUTOMATION", "Automation worker"),
                    ("TRY", "Try worker"),
                ],
                default="LANDING",
            ),
        ),
    ]
