# Generated by Django 5.2.7 on 2025-10-31 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_revisionlandingjob_commit_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="type",
            field=models.CharField(
                choices=[
                    ("LANDING", "Landing worker"),
                    ("AUTOMATION", "Automation worker"),
                    ("UPLIFT", "Uplift worker"),
                ],
                default="LANDING",
            ),
        ),
        migrations.CreateModel(
            name="MultiTrainUpliftRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_revision_ids", models.JSONField(default=list)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uplift_request",
                        to="main.upliftassessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RevisionUpliftJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("index", models.IntegerField(blank=True, null=True)),
                (
                    "revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.revision",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UpliftJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("SUBMITTED", "Submitted"),
                            ("IN_PROGRESS", "In progress"),
                            ("DEFERRED", "Deferred"),
                            ("FAILED", "Failed"),
                            ("LANDED", "Landed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=32,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("landed_commit_id", models.TextField(blank=True, default="")),
                ("requester_email", models.CharField(default="", max_length=255)),
                ("attempts", models.IntegerField(default=0)),
                ("priority", models.IntegerField(default=0)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("created_revision_ids", models.JSONField(blank=True, default=list)),
                (
                    "error_breakdown",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "multi_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="uplift_jobs",
                        to="main.multitrainupliftrequest",
                    ),
                ),
                (
                    "target_repo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.repo",
                    ),
                ),
                (
                    "unsorted_revisions",
                    models.ManyToManyField(
                        related_name="uplift_jobs",
                        through="main.RevisionUpliftJob",
                        to="main.revision",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="revisionupliftjob",
            name="uplift_job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.upliftjob",
            ),
        ),
    ]
