# Generated by Django 5.2.5 on 2025-10-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_revisionlandingjob_commit_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="pull_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
