# Generated by Django 5.2.7 on 2025-10-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_alter_worker_type_multitrainupliftrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="upliftjob",
            name="error_breakdown",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
