# Generated by Django 5.2.6 on 2025-10-07 01:05

import django.contrib.postgres.fields
from django.db import migrations, models

import lando.main.models.repo


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0033_alter_worker_type_revisionupliftjob_upliftjob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="hooks",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "PreventSymlinksCheck",
                            "Check for symlinks introduced in the diff.",
                        ),
                        (
                            "TryTaskConfigCheck",
                            "Check for `try_task_config.json` introduced in the diff.",
                        ),
                        (
                            "PreventNSPRNSSCheck",
                            "Prevent changes to vendored NSPR directories.",
                        ),
                        (
                            "PreventSubmodulesCheck",
                            "Prevent introduction of Git submodules into the repository.",
                        ),
                        (
                            "CommitMessagesCheck",
                            "Check the format of the passed commit message for issues.",
                        ),
                        (
                            "WPTSyncCheck",
                            "Check the WPTSync bot is only pushing changes to relevant subset of the tree.",
                        ),
                        (
                            "BugReferencesCheck",
                            "Prevent commit messages referencing non-public bugs from try.",
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=lando.main.models.repo.get_default_hooks,
                null=True,
                size=None,
            ),
        ),
    ]
