# Generated by Django 5.2.5 on 2025-11-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_repo_hooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="pull_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
