# Generated by Django 5.2.5 on 2025-11-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_revision_pull_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="patches",
            field=models.TextField(blank=True, default=""),
        ),
    ]
