# Generated by Django 5.2.8 on 2025-11-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_revision_patches"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="pr_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
