# Generated by Django 5.2.8 on 2025-12-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_repo_pr_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configurationvariable",
            name="variable_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BOOL", "Boolean"),
                    ("INT", "Integer"),
                    ("JSON", "JSON object"),
                    ("STR", "String"),
                ],
                default="STR",
                max_length=4,
                null=True,
            ),
        ),
    ]
