# Generated by Django 5.2.8 on 2025-12-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_alter_configurationvariable_variable_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="add_reviewers_to_commit_message",
            field=models.BooleanField(default=True),
        ),
    ]
