# Generated by Django 5.2.8 on 2025-12-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_alter_repo_hooks_PreventDotGithubCheck"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="try_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
