# Generated by Django 5.2.8 on 2025-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_alter_repo_hooks_PreventDotGithubCheck"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingjob",
            name="is_pull_request_job",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
