# Generated by Django 5.2.8 on 2025-12-05 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_alter_repo_hooks_PreventDotGithubCheck"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingjob",
            name="handover_repo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handover_jobs",
                to="main.repo",
            ),
        ),
    ]
