# Generated by Django 5.2.8 on 2025-12-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_landingjob_is_pull_request_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="pull_base_sha",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="revision",
            name="pull_head_sha",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
