# Generated by Django 5.2.8 on 2025-12-08 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_landingjob_is_pull_request_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingjob",
            name="handover_repo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handover_jobs",
                to="main.repo",
            ),
        ),
        migrations.AddField(
            model_name="landingjob",
            name="is_handed_over",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
