# Generated by Django 5.2.8 on 2025-12-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0041_revision_pull_base_sha_revision_pull_head_sha"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="treeherder_name",
            field=models.CharField(
                blank=True, help_text="Name of the repo in TreeHerder"
            ),
        ),
    ]
