# Generated by Django 5.2.9 on 2026-01-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0042_landingjob_handover_repo_landingjob_is_handed_over"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="is_try",
            field=models.BooleanField(default=False),
        ),
    ]
