# Generated by Django 5.2.8 on 2025-12-19 01:00
from django.db import migrations, models

from lando.main.scm import SCMType


def use_hg_name_for_treeherder_name(apps, schema_editor):  # noqa: ANN001
    """Copy the repo name to the treeherder_name any pre-existing Hg repo."""
    Repo = apps.get_model("main", "Repo")
    for repo in Repo.objects.filter(scm_type=SCMType.HG):
        if "https://hg.mozilla.org/" in repo.url:
            repo.treeherder_name = repo.url.strip("/").split("/")[-1]
            repo.save()


def add_firefox_treeherder_name(apps, schema_editor):  # noqa: ANN001
    """Use the default branch name as the treeherder_name for any pre-existing Firefox repo."""
    Repo = apps.get_model("main", "Repo")
    for repo in Repo.objects.filter(scm_type=SCMType.GIT):
        if "firefox-" in repo.name:
            repo.treeherder_name = repo.default_branch
            repo.save()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0042_landingjob_handover_repo_landingjob_is_handed_over"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="treeherder_name",
            field=models.CharField(
                blank=True, help_text="Name of the repo in TreeHerder"
            ),
        ),
        migrations.RunPython(
            use_hg_name_for_treeherder_name, migrations.RunPython.noop
        ),
        migrations.RunPython(add_firefox_treeherder_name, migrations.RunPython.noop),
    ]
