# Generated by Django 5.2.8 on 2025-12-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0042_landingjob_handover_repo_landingjob_is_handed_over"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="try_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
