# Generated by Django 5.2.9 on 2026-01-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0043_repo_treeherder_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="is_try",
            field=models.BooleanField(default=False),
        ),
    ]
