# Generated by Django 5.2.10 on 2026-02-02 02:09

import django.contrib.postgres.fields
from django.db import migrations, models

import lando.main.models.repo


def enable_prevent_hg_directory_check_hook(apps, schema_editor):  # noqa: ANN001
    """Enable the Prevent Hg Directory Check for all repos."""
    Repo = apps.get_model("main", "Repo")
    for repo in Repo.objects.all():
        repo.hooks.append("PreventHgDirectoryCheck")
        repo.save()


def disable_prevent_hg_directory_check_hook(apps, schema_editor):  # noqa: ANN001
    """Disable the Prevent Hg Directory Check for all repos."""
    Repo = apps.get_model("main", "Repo")
    for repo in Repo.objects.all():
        repo.hooks = [hook for hook in repo.hooks if hook != "PreventHgDirectoryCheck"]
        repo.save()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0043_repo_treeherder_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="hooks",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "PreventSymlinksCheck",
                            "Check for symlinks introduced in the diff.",
                        ),
                        (
                            "TryTaskConfigCheck",
                            "Check for `try_task_config.json` introduced in the diff.",
                        ),
                        (
                            "PreventDotGithubCheck",
                            "Prevent changes to GitHub workflows directory.",
                        ),
                        (
                            "PreventHgDirectoryCheck",
                            "Prevent patches from modifying .hg/ directory.",
                        ),
                        (
                            "PreventNSPRNSSCheck",
                            "Prevent changes to vendored NSPR directories.",
                        ),
                        (
                            "PreventSubmodulesCheck",
                            "Prevent introduction of Git submodules into the repository.",
                        ),
                        (
                            "CommitMessagesCheck",
                            "Check the format of the passed commit message for issues.",
                        ),
                        (
                            "WPTSyncCheck",
                            "Check the WPTSync bot is only pushing changes to relevant subset of the tree.",
                        ),
                        (
                            "BugReferencesCheck",
                            "Prevent commit messages referencing non-public bugs from try.",
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=lando.main.models.repo.get_default_hooks,
                null=True,
                size=None,
            ),
        ),
        migrations.RunPython(
            enable_prevent_hg_directory_check_hook,
            disable_prevent_hg_directory_check_hook,
        ),
    ]
