# Generated by Django 5.2.11 on 2026-02-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0044_alter_repo_hooks_PreventHgDirectoryCheck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="scm_type",
            field=models.CharField(
                blank=True,
                choices=[("git", "Git"), ("hg", "Mercurial")],
                default=None,
                help_text="Automatically detected upon saving, will match the type of the remote repo.",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="scm",
            field=models.CharField(
                choices=[("git", "Git"), ("hg", "Mercurial")],
                default="hg",
                max_length=3,
            ),
        ),
    ]
