# Generated by Django 5.2.11 on 2026-02-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0045_alter_repo_scm_type_alter_worker_scm"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="is_try",
            field=models.BooleanField(default=False),
        ),
    ]
