# Generated by Django 6.0.2 on 2026-03-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_repo_is_try"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repo",
            name="product_details_url",
        ),
    ]
