# Generated by Django 6.0.3 on 2026-03-20 06:51

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0047_remove_repo_product_details_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="pulse_routing_key",
            field=models.CharField(
                default="gitpushes",
                help_text="AMQP routing key to use when sending Pulse messages, as dot-separated words (example: `gitpushes.firefox`, default: `gitpushes` or overriden by `PULSE_ROUTING_KEY`)",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\w[\\.\\w]+$", flags=re.RegexFlag["ASCII"]
                    )
                ],
            ),
        ),
    ]
