# Generated by Django 6.0.3 on 2026-04-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0048_repo_pulse_routing_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phabricator_phid",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
