# Generated by Django 6.0.4 on 2026-04-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0049_profile_phabricator_phid"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="required_automation_permission",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The permission required to use the automation API against this repo. For example, main.scm_allow_direct_push.",
            ),
        ),
    ]
