# Generated by Django 6.0.4 on 2026-04-17 09:42

import django.contrib.postgres.fields
from django.db import migrations, models

import lando.main.models.repo


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0050_repo_required_automation_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="hooks",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "PreventSymlinksCheck",
                            "Check for symlinks introduced in the diff.",
                        ),
                        (
                            "TryTaskConfigCheck",
                            "Check for `try_task_config.json` introduced in the diff.",
                        ),
                        (
                            "PreventDotGithubCheck",
                            "Prevent changes to GitHub workflows directory.",
                        ),
                        (
                            "PreventHgDirectoryCheck",
                            "Prevent patches from modifying .hg/ directory.",
                        ),
                        (
                            "PreventNSPRNSSCheck",
                            "Prevent changes to vendored NSPR directories.",
                        ),
                        (
                            "PreventSignedCommitsCheck",
                            "Prevent patches from introducing signed commits.",
                        ),
                        (
                            "PreventSubmodulesCheck",
                            "Prevent introduction of Git submodules into the repository.",
                        ),
                        (
                            "CommitMessagesCheck",
                            "Check the format of the passed commit message for issues.",
                        ),
                        (
                            "WPTSyncCheck",
                            "Check the WPTSync bot is only pushing changes to relevant subset of the tree.",
                        ),
                        (
                            "BugReferencesCheck",
                            "Prevent commit messages referencing non-public bugs from try.",
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=lando.main.models.repo.get_default_hooks,
                null=True,
            ),
        ),
    ]
