# Generated by Django 6.0.4 on 2026-05-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0051_alter_repo_hooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="maintenance_interval_seconds",
            field=models.IntegerField(default=300),
        ),
    ]
