# Generated by Django 6.0.5 on 2026-05-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='maintenance_interval_seconds',
            field=models.IntegerField(default=300),
        ),
    ]
