# Generated by Django 6.0.5 on 2026-06-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_worker_maintenance_interval_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='autoformat_setup_commands',
            field=models.JSONField(blank=True, default=list, help_text="Ordered list of command arg-lists run at worker startup to set up this repo's formatter toolchains. Each entry is a list of arguments passed to `./mach` (without `./mach` itself). Populated with the default `mach artifact` sequence on save when `autoformat_enabled` is set, unless explicitly provided; left empty otherwise."),
        ),
    ]
