# Generated by Django 6.0.5 on 2026-06-02 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_repo_autoformat_setup_commands'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoformatChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commit_sha', models.CharField(max_length=40)),
                ('changed_files', models.JSONField(default=list)),
                ('diff', models.TextField(blank=True, default='')),
                ('landing_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoformat_changes', to='main.landingjob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
