# Generated by Django 6.0.5 on 2026-06-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_autoformatchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='autoformat_run_command',
            field=models.JSONField(blank=True, default=list, help_text='Command arg-list run to apply autoformatting to the patch stack. The entry is a list of arguments passed to `./mach` (without `./mach` itself). Populated with the default `mach format` command on save when `autoformat_enabled` is set, unless explicitly provided; left empty otherwise.'),
        ),
    ]
