# Generated by Django 6.0.5 on 2026-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_autoformatchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='encrypted_gh_hmac_secret',
            field=models.BinaryField(blank=True, default=b''),
        ),
    ]
