# Generated by Django 6.0.5 on 2026-06-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_autoformatchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='base_revision',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
