# Generated by Django 6.0.6 on 2026-06-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_repo_autoformat_run_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='base_revision',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
