# Generated by Django 6.0.5 on 2026-06-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_repo_autoformat_run_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diffwarning',
            name='diff_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
