# Generated by Django 6.0.5 on 2026-06-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_diffwarning_diff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmap',
            name='git_hash',
            field=models.CharField(db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='commitmap',
            name='hg_hash',
            field=models.CharField(db_index=True, default='', max_length=40),
        ),
    ]
