# Generated by Django 6.0.6 on 2026-06-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_revision_base_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='three_way_merge_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
