# Generated by Django 6.0.6 on 2026-06-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_worker_three_way_merge_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingjob',
            name='landing_strategy',
            field=models.CharField(blank=True, choices=[('THREE_WAY', '3-way merge (reconstructed at base and rebased)'), ('TWO_WAY', '2-way apply (applied at the target tip)')], default=None, max_length=16, null=True),
        ),
    ]
