# Generated by Django 6.0.6 on 2026-06-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_commitmap_git_hash_alter_commitmap_hg_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingjob',
            name='landing_strategy',
            field=models.CharField(blank=True, choices=[('THREE_WAY', '3-way merge (reconstructed at base and rebased)'), ('TWO_WAY', '2-way apply (applied at the target tip)')], default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='base_revision',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='worker',
            name='three_way_merge_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
