# Generated by Django 6.0.6 on 2026-06-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_landingjob_landing_strategy_revision_base_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upliftsubmission',
            name='target_selection_method',
            field=models.CharField(choices=[('widget_version', 'Widget (version)'), ('widget_manual', 'Widget (manual)'), ('server_rendered', 'Server-rendered')], default='server_rendered', max_length=20),
        ),
    ]
