# Generated by Django 6.0.6 on 2026-07-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_upliftsubmission_target_selection_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingjob',
            name='git_branch',
            field=models.CharField(blank=True, default=''),
        ),
    ]
