# Generated by Django 6.0.6 on 2026-07-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_upliftsubmission_target_selection_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='commit_map_name',
            field=models.CharField(blank=True, help_text='Name of the CommitMap to use (matches the git_repo_name of the entries)'),
        ),
    ]
