# Generated by Django 6.0.6 on 2026-07-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_repo_encrypted_gh_hmac_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='approval_required',
            field=models.BooleanField(default=False, help_text='Mark this repo as accepting Uplifts. If True, this repo will be presented to users as a train to uplift to.'),
        ),
    ]
