# Generated by Django 6.0.6 on 2026-07-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_repo_encrypted_gh_hmac_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='commit_map_name',
            field=models.CharField(blank=True, default='', help_text='Name of the CommitMap to use (matches the git_repo_name of the entries)'),
        ),
    ]
