# Generated by Django 6.0.6 on 2026-08-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_repo_approval_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='force_push',
            field=models.BooleanField(default=False, help_text='Allow force-pushes to the repo (e.g., change of history or new heads). Necessary for try repos.'),
        ),
    ]
