# Generated by Django 6.0.6 on 2026-08-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_alter_repo_force_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingjob',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('IN_PROGRESS', 'In progress'), ('DEFERRED', 'Deferred'), ('FAILED', 'Failed'), ('LANDED', 'Landed'), ('CANCELLED', 'Cancelled'), ('ABORTED', 'Aborted')], db_index=True, default='CREATED', max_length=32),
        ),
        migrations.AlterField(
            model_name='upliftjob',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('IN_PROGRESS', 'In progress'), ('DEFERRED', 'Deferred'), ('FAILED', 'Failed'), ('LANDED', 'Landed'), ('CANCELLED', 'Cancelled'), ('ABORTED', 'Aborted')], db_index=True, default='CREATED', max_length=32),
        ),
    ]
