# Generated by Django 6.0.6 on 2026-09-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_alter_landingjob_status_alter_upliftjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='upliftassessment',
            name='bug_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
