# Generated by Django 6.0.6 on 2026-09-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0066_upliftassessment_bug_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingjob",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="landingjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="upliftjob",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="upliftjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="current_job_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="process_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
