# Generated by Django 6.1.2 on 2026-10-09 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0067_repo_status_flag_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingjob",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="landingjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="upliftjob",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="upliftjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="current_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.landingjob",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="process_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="retry_interrupted_jobs",
            field=models.BooleanField(
                default=False,
                help_text="Retry interrupted landing jobs when this worker restarts. May repeat a push completed before the worker crashed.",
            ),
        ),
    ]
