# Generated by Django 5.2.4 on 2025-09-11 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0029_upliftassessment_upliftrevision"),
    ]

    operations = [
        migrations.CreateModel(
            name="TryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("IN_PROGRESS", "In progress"),
                            ("DEFERRED", "Deferred"),
                            ("FAILED", "Failed"),
                            ("LANDED", "Landed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default=None,
                        max_length=32,
                        null=True,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("landed_commit_id", models.TextField(blank=True, default="")),
                (
                    "requester_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("priority", models.IntegerField(default=0)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("target_commit_hash", models.TextField(blank=True, default="")),
                (
                    "target_repo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.repo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TryAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField()),
                ("order", models.PositiveIntegerField()),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="try_api.tryjob",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
