# Generated by Django 5.2.4 on 2025-09-16 05:57

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("try_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tryjob",
            name="target_commit_hash",
            field=models.TextField(
                default="",
                help_text="The published base commit on which to apply `patches`.",
                max_length=40,
                validators=[
                    django.core.validators.MaxLengthValidator(40),
                    django.core.validators.MinLengthValidator(40),
                    django.core.validators.RegexValidator("^([a-fA-F0-9])+"),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tryjob",
            name="base_commit_vcs",
            field=models.CharField(
                blank=True,
                choices=[("git", "Git"), ("hg", "Mercurial")],
                default=None,
                help_text="The VCS that the `base_commit` hash is based on.",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tryjob",
            name="patch_format",
            field=models.CharField(
                choices=[
                    ("git-format-patch", "Git Format Patch"),
                    ("hgexport", "Hgexport"),
                ],
                default="git-format-patch",
                help_text="The format of the encoded patches in `patches`.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tryjob",
            name="patches",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    validators=[
                        django.core.validators.RegexValidator("^[A-Za-z0-9+/]+={0,2}$")
                    ]
                ),
                default="{}",
                help_text="Ordered array of base64 encoded patches for submission to Lando.",
                size=None,
            ),
        ),
        migrations.DeleteModel(
            name="TryAction",
        ),
        migrations.AlterField(
            model_name="tryjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("IN_PROGRESS", "In progress"),
                    ("DEFERRED", "Deferred"),
                    ("FAILED", "Failed"),
                    ("LANDED", "Landed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="SUBMITTED",
                max_length=32,
            ),
        ),
    ]
