# Generated by Django 5.2.4 on 2025-09-17 01:39

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "try_api",
            "0002_remove_tryjob_target_commit_hash_tryjob_base_commit_and_more_squashed_0004_alter_tryjob_patches_alter_tryjob_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tryjob",
            name="patches",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    validators=[
                        django.core.validators.RegexValidator("^[A-Za-z0-9+/]+={0,2}$")
                    ]
                ),
                default=list,
                help_text="Ordered array of base64 encoded patches for submission to Lando.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="tryjob",
            name="requester_email",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="tryjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("SUBMITTED", "Submitted"),
                    ("IN_PROGRESS", "In progress"),
                    ("DEFERRED", "Deferred"),
                    ("FAILED", "Failed"),
                    ("LANDED", "Landed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="CREATED",
                max_length=32,
            ),
        ),
    ]
