# Generated by Django 5.2.6 on 2025-09-19 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0039_alter_worker_type"),
        ("try_api", "0005_alter_tryjob_patches_alter_tryjob_requester_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tryjob",
            name="attempts",
        ),
        migrations.RemoveField(
            model_name="tryjob",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="tryjob",
            name="duration_seconds",
        ),
        migrations.RemoveField(
            model_name="tryjob",
            name="error",
        ),
        migrations.RemoveField(
            model_name="tryjob",
            name="id",
        ),
        migrations.RemoveField(
            model_name="tryjob",
            name="landed_commit_id",
        ),
        migrations.RemoveField(
            model_name="tryjob",
            name="patches",
        ),
        migrations.RemoveField(
            model_name="tryjob",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="tryjob",
            name="requester_email",
        ),
        migrations.RemoveField(
            model_name="tryjob",
            name="status",
        ),
        migrations.RemoveField(
            model_name="tryjob",
            name="target_commit_hash",
        ),
        migrations.RemoveField(
            model_name="tryjob",
            name="target_repo",
        ),
        migrations.RemoveField(
            model_name="tryjob",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="tryjob",
            name="landingjob_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="main.landingjob",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tryjob",
            name="base_commit_vcs",
            field=models.CharField(
                blank=True,
                choices=[("git", "Git"), ("hg", "Mercurial")],
                default=None,
                help_text="The VCS that the `target_commit_hash` is based on.",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tryjob",
            name="patch_format",
            field=models.CharField(
                choices=[
                    ("git-format-patch", "Git Format Patch"),
                    ("hgexport", "Hgexport"),
                ],
                default="git-format-patch",
                help_text="The format of the patches stored as Revisions.",
                max_length=16,
            ),
        ),
    ]
