# Generated by Django 5.2.6 on 2025-09-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("try_api", "0006_remove_tryjob_attempts_remove_tryjob_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tryjob",
            name="base_commit_vcs",
        ),
        migrations.RemoveField(
            model_name="tryjob",
            name="patch_format",
        ),
    ]
