name: Build and test

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build -t lando .
      - name: Test
        run: make test
