# Generated by Django 6.0.6 on 2026-08-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treestatus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tree",
            name="is_retired",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Retired trees are hidden from the Treestatus web view and API, though their historical data is retained.",
            ),
        ),
    ]
