# Generated by Django 6.0.6 on 2026-08-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treestatus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tree",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive trees are hidden from the Treestatus web view and the API list endpoints. They can still be requested by name, and their historical data is retained.",
            ),
        ),
    ]
